[tool.poetry]
name = "random-forest-mc"
version = "1.0.1"
description = "This project is about use Random Forest approach using a dynamic tree selection Monte Carlo based."
authors = ["Israel Oliveira <israel.oliveira@gmail.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/ysraell/random-forest-mc"
repository = "https://github.com/ysraell/random-forest-mc"
keywords = ["random forest", "random"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.7.13,<3.11"
pandas = ">=1.3"
numpy = ">=1.20"
tqdm = ">=4.60"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
coverage = "^5.5"
pytest-cov = "^2.12.1"
flake8 = "^3.9.2"
black = "^21.7b0"
pre-commit = "^2.14.0"
pytest_check = "^1.0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
